language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -it titustwimbly/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true titustwimbly/docker-react npm run test -- --coverage
